### ISSUE TITLE
containedtextで大文字アルファベットを使うと検出できてない気がする

### ISSUE THREAD

**Issue by turu64** [Kisame3957/ItemChecker#1]
ItemChecker version 1.0.1-1.20
git-Paper-83 (MC: 1.20.1)

testitemならいけるけどTESTITEMだと動かない
```
test:
  checknbt: test
  checklist:
    setting1:
      containedtext: TESTITEM
      consolecommand: wm give %player% 357_Magnum
```
